# Generated by Django 2.0 on 2019-04-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
        ('read_statistics', '0002_readtatil'),
    ]

    operations = [
    ]
