# Generated by Django 2.0 on 2019-04-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_merge_20190407_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readtatil',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Readtatil',
        ),
    ]
