# Generated by Django 2.0 on 2019-04-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190329_1850'),
        ('blog', '0007_auto_20180224_0212'),
    ]

    operations = [
    ]
